- .github/workflows/build.yml
- .github/workflows/upgrade.yml
- .projen/deps.json
- .projen/tasks.json
- .projenrc.ts
- nx.json
- package.json
- packages/stacks/api/src/gh.ts
- pnpm-lock.yaml
> feat(projenrc): setup and connect nx-workspace, add ccu bot

- .projenrc.ts
- packages/stacks/api/tsconfig.dev.json
- packages/stacks/api/tsconfig.json
> fix(stacks.api): include config file in tsconfig.dev, not tsconfig

- packages/stacks/api/src/stacks/index.ts
- packages/stacks/api/test/__snapshots__/cache-stack.spec.ts.snap
- packages/stacks/api/test/cache-stack.spec.ts
- packages/stacks/api/test/main.spec.ts
- test(stacks.api): update main spec to resolve type issues
- test(stacks.api): add test suite for cache stack
- test(stacks.api): update snapshots
Fixes #
> test(stacks.api): cache stack test suite

- .github/workflows/deploy.yml
- packages/stacks/api/src/main.ts
- packages/stacks/api/src/pipeline.ts
- scripts/update-config-schema.ts
- fix(scripts): use seen strategy to resolve charts reference issues
- feat(stacks.api/pipeline): add conditional cache stack to pipeline
- feat(stacks.api): add stage definition for production
- ci(deploy): update synthesized workflow
Fixes #
> feat(stacks.api): add production to pipeline

- .projenrc.ts
- packages/stacks/api/.projen/tasks.json
- packages/stacks/maintenance-site/.projen/tasks.json
> fix(projenrc): ensure bash is used for synth conditions

- .gitignore
- .projenrc.ts
- packages/config/src/schema.ts
- packages/stacks/api/src/gh.ts
- packages/stacks/api/src/main.ts
- packages/stacks/api/src/pipeline.ts
- chore(projenrc): add .env.\* ignore pattern
- feat(config): add pipeline config schema
- feat(stacks.api): use repositories list from pipeline config for oidc authentication
Fixes #
> feat: add pipeline config, use config to source repo allowlist for oidc

- .github/workflows/deploy-maintenance-site.yml
- packages/construct/awscdk/github-pipeline/src/s3.ts
- packages/construct/awscdk/github-pipeline/test/__snapshots__/workflow.spec.ts.snap
- fix(construct.awscdk.github-pipeline): use `cp` for copy action, infer step name
- test(construct.awscdk.github-pipeline): update snapshots
Fixes #
> fix(construct.awscdk.github-pipeline): Use `cp` for copy action in S3 Bucket Step

- .envrc
- .github/workflows/deploy-maintenance-site.yml
- .github/workflows/deploy.yml
- .projenrc.ts
- .tool-versions
- packages/construct/awscdk/github-pipeline/src/pipeline-stack.ts
- packages/construct/awscdk/github-pipeline/src/workflow.ts
- packages/construct/awscdk/github-pipeline/test/__snapshots__/workflow.spec.ts.snap
- packages/construct/awscdk/github-pipeline/test/workflow.spec.ts
- packages/stacks/api/src/gh.ts
- packages/stacks/maintenance-site/src/main.ts
- feat(projenrc): update awscli, expose tool versions via envrc
- feat(construct.awscdk.pipelines): add pre and post publish build steps props to `GithubWorkflowPipeline`
- fix(construct.awscdk.github-pipeline): cancel-in-progress not set when false in workflow concurrecny
- feat(construct.awscdk.github-pipeline): builder methods for pre/post publish steps
- feat(construct.awscdk.github-pipeline): tool install methods and parameters
- test(construct.awscdk.github-pipeline): unit tests for multi-stage, code pipeline, related
- test(construct.awscdk.github-pipeline): update snapshots
- feat(stacks.maintenance-site): setup tools with new builder methods
- feat(stacks.api): setup pipeline tools via new builder methods
Fixes #
> feat(construct.awscdk.github-pipeline): Pipeline builder methods for tools, allow target version overrides, fixes

- .github/workflows/deploy-maintenance-site.yml
- .github/workflows/deploy.yml
- packages/construct/awscdk/github-pipeline/src/workflow.ts
- packages/construct/awscdk/github-pipeline/test/__snapshots__/workflow.spec.ts.snap
- feat(construct.awscdk.github-pipeline): upload assets as a single parallelized job
- ci(deploy): update synthesized workflows
Fixes #
> feat(construct.awscdk.github-pipeline): upload assets as a single parallelized job

- .github/workflows/deploy-maintenance-site.yml
- .github/workflows/deploy.yml
- packages/construct/awscdk/github-pipeline/src/pipeline-stack.ts
- packages/construct/awscdk/github-pipeline/test/__snapshots__/workflow.spec.ts.snap
- fix(construct.awscdk.github-pipeline): do not specify explicit runner label in runner related checks
- ci(deploy): update synthesized deploy flows
Fixes #
> fix(construct.awscdk-github-pipeline): do not specify explicit label in runner related checks

- .projenrc.ts
- packages/stacks/api/.projen/deps.json
- packages/stacks/api/.projen/tasks.json
- packages/stacks/api/package.json
- packages/stacks/api/src/addons/arc.ts
- packages/stacks/api/src/addons/index.ts
- packages/stacks/api/src/schema.ts
- pnpm-lock.yaml
- feat(stacks.api): add debug as dependency
- feat(stacks.api/addons): `ARCScaleSetController` and `ARCScaleSet` helm addons
- feat(stacks.api): arc schema config
Fixes #
> feat(stacks.api/addons): Actions Runner Controller ScaleSetController and ScaleSet addons

- packages/stacks/api/src/cluster.ts
- packages/stacks/api/src/pipeline.ts
- packages/stacks/api/src/schema.ts
> feat(stacks.api): add instanceTypes config and karpenter option

- .projenrc.ts
- projenrc/builders.ts
- feat(projenrc): implement `CdkTsAppCompileBuilder`
- refactor(projenrc): use `CdkTsAppCompileBuilder` for maintenance stack
- refactor(projenrc): use `CdkTsAppCompileBulider` for api stack
Fixes #
> feat(projenrc): `CdkkTsAppCompileBuilder` for common cdk app configuration

- packages/stacks/api/src/addons/arc.ts
> feat(stacks.api/addons): provision ephemeral volumes via ebs for worker/docker volume claims

- packages/config/src/config.ts
> fix(configs): fail hard on failure to resolve giget auth token

- .projenrc.ts
- packages/construct/awscdk/pdf-renderer/.projen/tasks.json
- packages/construct/awscdk/pdf-renderer/project.json
> fix(projenrc): add lambda assets as nx outputs

- packages/stacks/api/src/addons/arc.ts
> feat(stacks.api/addons): default imagePullPolicy to `IfNotPresent` to reduce startup times

- .github/workflows/deploy.yml
- packages/stacks/api/src/gh.ts
- packages/stacks/api/src/main.ts
- packages/stacks/api/src/pipeline.ts
- packages/stacks/api/src/stacks/data.ts
- packages/stacks/api/src/stacks/index.ts
- packages/stacks/api/src/stacks/zones.ts
- feat(stacks.api): `DelegatorZoneStack` and `DelegatedHostedZone` construct
- --wip-- [skip ci]
Fixes #
> feat(stacks.api/stacks): Delegated Hosted Zones

- arc-runner/Dockerfile
- arc-runner/docker-bake.hcl
- packages/stacks/api/src/addons/arc.ts
- packages/stacks/api/src/main.ts
- feat(stacks.api/addons/arc): extract `templateVolumes` and `templateVolumeMounts`, ensure per-pod separate vol mounts, use tmp memory
- feat(stacks.api/addons/arc): support dind in runner pattern via `useDindRunner` option
- feat(arc): add dockerfile for arc-runner
- feat(stacks.api/addons/arc): use custom arc runner image
Fixes #
> feat(stacks.api/addons/arc): ARC Runner custom image + stability improvements

- packages/stacks/api/src/addons/arc.ts
> feat(stacks.api/addons/arc): add retained docker sc for var docker, fix missing var docker mount

- packages/stacks/api/src/addons/arc.ts
> feat(stacks.api/addons/arc): adjust dind resources, fix missing runner resources

- packages/stacks/api/src/addons/arc.ts
> fix(stacks.api/addons/arc): prevent karpenter from evicting ephemeral runners

- packages/stacks/api/src/cluster.ts
> feat(stacks.api): bump karpenter version to v0.30.0

- packages/stacks/api/src/addons/arc.ts
> fix(stacks.api/addons/arc): update arc runner container resources

- packages/stacks/api/src/addons/arc.ts
> fix(stacks.api/addons/arc): more sane runner resource allotments

- packages/stacks/api/src/addons/arc.ts
> fix(stacks.api/addons/arc): increase runner arc limits

- arc-runner/Dockerfile
- arc-runner/docker-bake.hcl
> feat(arc): add python3-venv, setup pipx in arc runner image

- packages/charts/crisiscleanup/src/lib/crisiscleanup.ts
- packages/charts/crisiscleanup/src/schema.ts
- packages/charts/crisiscleanup/test/__snapshots__/main.spec.ts.snap
- packages/charts/crisiscleanup/test/main.spec.ts
- packages/k8s/construct/api/src/index.ts
- packages/k8s/construct/api/src/sync.ts
- packages/k8s/construct/api/src/types.ts
- packages/k8s/construct/component/src/container-image.ts
- packages/stacks/api/src/addons/arc.ts
- packages/stacks/api/src/addons/crisiscleanup.ts
- feat(k8s.construct.api): implement `DatabaseSync` construct for api db sync
- feat(k8s.construct.components): extract `IContainerImage`
- feat(k8s.construct.api): add `sync` field to `ApiConstructConfig`
- feat(charts.ccu): `CronOptions` and `syncSchema`
- feat(charts.ccu): add `sync` property to ccu chart
- feat(stacks.api): mount csi secret volumes on `sync` construct if found
- feat(k8s.construct.api): add container to cron job
- test(charts.ccu): add unit test for chart with sync
- test(charts.ccu): update snapshots
Fixes #
> feat: API Database Sync

- arc-runner/Dockerfile
- arc-runner/docker-bake.hcl
- packages/stacks/api/src/addons/arc.ts
- feat(arc-runner): update dockerfile to 2.311.0, install buildx, update docker version, runner-hooks version
- feat(arc-runner): update tag in bake file
- feat(stacks.api/addons): update default arc version to 0.7.0
Fixes #
> feat(arc): upgrade arc addon to 0.7.0, update runner image to v2.311.0

- packages/stacks/api/src/addons/arc.ts
> fix(stacks.api/addons): increase arc docker volume size to 20gb

- packages/stacks/api/src/addons/arc.ts
> fix(stack.ap/addons): increase arc worker space to 20gi

- packages/config/src/schema.ts
- packages/stacks/api/src/main.ts
- packages/stacks/api/src/pipeline.ts
- feat(config.schema): add `appRegistryTag` to pipeline config schema
- feat(stacks.api): tag all stacks with myApplication tag
Fixes #
> feat(stacks.api): tag all stacks with aws myApplication tag

- .github/workflows/deploy-au-offline-site.yml
- packages/stacks/maintenance-site/src/maintenance-site.ts
> fix(stacks.maintenance-site): explicit dependency to resolve workflow generation issue

- .github/workflows/deploy.yml
- packages/construct/awscdk/github-pipeline/src/checkout.ts
- packages/construct/awscdk/github-pipeline/src/pipeline-stack.ts
- packages/construct/awscdk/github-pipeline/test/__snapshots__/workflow.spec.ts.snap
- fix(construct.awscdk.github-pipeline): update default action versions
- test(construct.awscdk.github-pipeline): update snapshots
Fixes #
> fix(construct.awscdk.github-pipeline): update default actions versions

- .github/workflows/deploy-crisiscleanup-site.yml
- .projenrc.ts
- packages/stacks/web/.projen/deps.json
- packages/stacks/web/package.json
- packages/stacks/web/src/main.ts
- packages/stacks/web/src/web.ts
- packages/stacks/web/tsconfig.json
- pnpm-lock.yaml
- feat(stacks.web): add `construct.awscdk.cloudfront-url-rewrite` as workspace dep
- ci(deploy-web): update web deploy flow
- feat(stacks.web): add blog redirect to web staging
Fixes #
> feat(stacks.web): add blog redirect to web staging

- packages/stacks/web/src/web.ts
> feat(stacks.web): setup blog zone record and certificate if `enableBlogRedirect`

- arc-runner/Dockerfile
- arc-runner/docker-bake.hcl
> feat(arc): update arc runner to v2.319.1, update docker/buildx/compose

- packages/stacks/web/src/main.ts
> feat(stacks.web): enable blog redirect for web production

- packages/config/src/schema.ts
> feat(config/schema): add `hostReplica` to config secrets schema

- arc-runner/Dockerfile
- arc-runner/docker-bake.hcl
> feat(arc): update runner version to v2.320, buildx, compose versions

- packages/stacks/api/src/addons/arc.ts
see: https://github.com/actions/actions-runner-controller/issues/3021
Fixes #
> feat(stacks.api/addons/arc): increase `runnerMaxConcurrentReconciles` to 8

- packages/config/src/schema.ts
> feat(config.schema): add ipstack secrets schema

- arc-runner/Dockerfile
- arc-runner/docker-bake.hcl
> feat(arc-runner): update arc-runner version, update hooks, docker/docker compose/ docker buildx versions

- packages/config/src/schema.ts
> feat(config.schema): add notifications secrets schema, slack notifs schema
